### ISSUE TITLE
Error using ONNX T5 model exported from Optimum

### ISSUE THREAD

**Issue by GarciaLnk** [visheratin/web-ai#5]
I'm not able to run a T5 model exported to ONNX using Optimum, although it works when I use fastT5 to export it.

Error:
```
Uncaught (in promise) TypeError: encoderOutput is undefined
    process t5model.js:23
    generate generator.js:8
```

Command used to export a FLAN-T5 model to ONNX:
`optimum-cli export onnx --for-ort --model google/flan-t5-base --task seq2seq-lm models/flan-t5-base_onnx/`

Code used to run the model (based on the example):
```
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const [output, setOutput] = useState({ value: "Output" });

  useEffect(() => {
    loadModel();
  }, []);

  const [model, setModel] = useState({});

  const [status, setStatus] = useState({ message: "ready", processing: false });

  const loadModel = async () => {
    setStatus({ message: "loading the model", processing: true });

    const metadata: TextMetadata = {
      modelPaths: new Map<string, string>([
        [
          "encoder",
          "/models/flan-t5-base_onnx/encoder_model.onnx",
        ],
        [
          "decoder",
          "/models/flan-t5-base_onnx/decoder_model.onnx",
        ],
      ]),
      tokenizerPath: "https://edge-ai-models.s3.us-east-2.amazonaws.com/text/seq2seq/grammar-correction/t5-tiny/tokenizer.json",
      id: "flan-t5-base",
    }

    const model = new Seq2SeqModel(metadata);
    const elapsed = await model.init();
    console.log(elapsed);

    setModel({ instance: model });
    setStatus({ message: "ready", processing: false });
  };

  const process = async () => {
    if (!inputRef.current || !model) {
      return;
    }
    const value = inputRef.current?.value;
    if (value === "" || value === undefined) {
      return;
    }
    setStatus({ message: "processing", processing: true });
    let output = "";
    // @ts-ignore
    for await (const piece of model.instance.processStream(value)) {
      output = output.concat(piece);
      output = output.replace(" .", ".");
      setOutput({ value: output });
    }
    setStatus({ message: "finished processing", processing: false });
  };
```

**Comment by visheratin** [comment]
Thank you for reporting the issue!

I see that there are differences in the input and output formats between the models exported via fastT5 and optimum. Right now, I'm rewriting tokenization logic to support all language models from the Hugging Face hub. As soon as I finish, I will look into integrating the models exported with optimum.

**Comment by visheratin** [comment]
I just published the new version of the package that addresses the issue.

For the test, I exported the model using the command you provided and tested using the following metadata:
```
{
  id: "t5-test",
  title: "T5 test",
  description: "",
  type: TextModelType.Seq2Seq,
  sizeMB: 330,
  modelPaths: new Map<string, string>([
    ["encoder", "https://edge-ai-models.s3.us-east-2.amazonaws.com/text/test/text/t5-optimum/encoder_model.onnx"],
    ["decoder", "https://edge-ai-models.s3.us-east-2.amazonaws.com/text/test/text/t5-optimum/decoder_model.onnx"],
  ]),
  outputNames: new Map<string, string>([
    ["encoder", "last_hidden_state"],
    ["decoder", "logits"],
  ]),
  tokenizerPath: "https://huggingface.co/google/t5-efficient-tiny/resolve/main/tokenizer.json",
  tags: ["summarization", "t5"],
  prefixes: ["summarize"],
}
```

**Comment by GarciaLnk** [comment]
It seems to work now, however, I was trying to run a model with merged decoders (with and without past) as I saw [here](https://github.com/xenova/transformers.js/blob/main/scripts/convert.py), but I get an error related to a missing past input, so I guess decoders with past are still not supported. Let me know if you want me to open a separate issue with more details.

```
inference-session-impl.ts:95 Uncaught (in promise) Error: input 'past_key_values.0.decoder.key' is missing in 'feeds'.
    at InferenceSession.run (inference-session-impl.ts:95:15)
    at Session.run (session.ts:75:34)
    at Decoder.process (decoder.ts:30:39)
    at async generate (generator.ts:16:27)
    at async Seq2SeqModel.processStream (seq2seqModel.ts:159:22)
    at async background.ts:104:20
```

**Comment by visheratin** [comment]
Decoders with the past are deliberately not supported. When the decoded sequence becomes long, the tensor with the past becomes too large and slows down generation. If decoders with the past are needed for your use cases, please open a new issue, and I will return their support in one of the nearest releases.

**Comment by GarciaLnk** [comment]
I see, I was just curious to compare the performance. I'm closing this issue.
